### ISSUE TITLE
Release 0.1

### ISSUE THREAD

**Issue by giorgiop** [mystral-ai/devtale#29]
- [x] https://github.com/mystral-ai/devtale/issues/21
- [x] https://github.com/mystral-ai/devtale/issues/23
- [x] https://github.com/mystral-ai/devtale/issues/22
- [x] https://github.com/mystral-ai/devtale/issues/26
- [x] https://github.com/mystral-ai/devtale/issues/28

**Comment by betogaona7** [comment]
All issues closed
